/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-11-23 at 22:06:32 UTC 
 * Modify at your own risk.
 */

package com.appspot.umichseed.seed.model;

/**
 * ProtoRPC message definition to represent a user email and Google Cloud Messenger token associated
 * with their device
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the seed. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MessagesGcmCredsPut extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("new_reg_id")
  private java.lang.String newRegId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("old_reg_id")
  private java.lang.String oldRegId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public MessagesGcmCredsPut setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNewRegId() {
    return newRegId;
  }

  /**
   * @param newRegId newRegId or {@code null} for none
   */
  public MessagesGcmCredsPut setNewRegId(java.lang.String newRegId) {
    this.newRegId = newRegId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOldRegId() {
    return oldRegId;
  }

  /**
   * @param oldRegId oldRegId or {@code null} for none
   */
  public MessagesGcmCredsPut setOldRegId(java.lang.String oldRegId) {
    this.oldRegId = oldRegId;
    return this;
  }

  @Override
  public MessagesGcmCredsPut set(String fieldName, Object value) {
    return (MessagesGcmCredsPut) super.set(fieldName, value);
  }

  @Override
  public MessagesGcmCredsPut clone() {
    return (MessagesGcmCredsPut) super.clone();
  }

}
