/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-11-23 at 22:24:20 UTC 
 * Modify at your own risk.
 */

package com.appspot.umichseed.seed.model;

/**
 * ProtoRPC message definition to represent a set of patient qualitative data (over a period of
 * time)
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the seed. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MessagesPQualDataListResponse extends com.google.api.client.json.GenericJson {

  /**
   * ProtoRPC message definition to represent a set of survey responses
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("pdata_list")
  private java.util.List<MessagesPManDataPut> pdataList;

  static {
    // hack to force ProGuard to consider MessagesPManDataPut used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(MessagesPManDataPut.class);
  }

  /**
   * ProtoRPC message definition to represent a set of survey responses
   * @return value or {@code null} for none
   */
  public java.util.List<MessagesPManDataPut> getPdataList() {
    return pdataList;
  }

  /**
   * ProtoRPC message definition to represent a set of survey responses
   * @param pdataList pdataList or {@code null} for none
   */
  public MessagesPQualDataListResponse setPdataList(java.util.List<MessagesPManDataPut> pdataList) {
    this.pdataList = pdataList;
    return this;
  }

  @Override
  public MessagesPQualDataListResponse set(String fieldName, Object value) {
    return (MessagesPQualDataListResponse) super.set(fieldName, value);
  }

  @Override
  public MessagesPQualDataListResponse clone() {
    return (MessagesPQualDataListResponse) super.clone();
  }

}
