/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-26 at 18:49:56 UTC 
 * Modify at your own risk.
 */

package com.appspot.umichseed.seed.model;

/**
 * ProtoRPC message definition to represent a request for recent watson question/answer pairs
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the seed. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SeedApiMessagesWatsonQuestionsRequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("num_questions") @com.google.api.client.json.JsonString
  private java.lang.Long numQuestions;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getNumQuestions() {
    return numQuestions;
  }

  /**
   * @param numQuestions numQuestions or {@code null} for none
   */
  public SeedApiMessagesWatsonQuestionsRequest setNumQuestions(java.lang.Long numQuestions) {
    this.numQuestions = numQuestions;
    return this;
  }

  @Override
  public SeedApiMessagesWatsonQuestionsRequest set(String fieldName, Object value) {
    return (SeedApiMessagesWatsonQuestionsRequest) super.set(fieldName, value);
  }

  @Override
  public SeedApiMessagesWatsonQuestionsRequest clone() {
    return (SeedApiMessagesWatsonQuestionsRequest) super.clone();
  }

}
