/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-10-28 17:08:27 UTC)
 * on 2014-11-17 at 19:11:08 UTC 
 * Modify at your own risk.
 */

package com.appspot.umichseed.seed.model;

/**
 * ProtoRPC message definition to represent a set of patient quantitative data (over a period of
 * time)
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the seed. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SeedApiMessagesPQuantDataListResponse extends com.google.api.client.json.GenericJson {

  /**
   * ProtoRPC message definition to represent a single piece of patient data
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("pdata_list")
  private java.util.List<SeedApiMessagesPQuantDataResponse> pdataList;

  /**
   * ProtoRPC message definition to represent a single piece of patient data
   * @return value or {@code null} for none
   */
  public java.util.List<SeedApiMessagesPQuantDataResponse> getPdataList() {
    return pdataList;
  }

  /**
   * ProtoRPC message definition to represent a single piece of patient data
   * @param pdataList pdataList or {@code null} for none
   */
  public SeedApiMessagesPQuantDataListResponse setPdataList(java.util.List<SeedApiMessagesPQuantDataResponse> pdataList) {
    this.pdataList = pdataList;
    return this;
  }

  @Override
  public SeedApiMessagesPQuantDataListResponse set(String fieldName, Object value) {
    return (SeedApiMessagesPQuantDataListResponse) super.set(fieldName, value);
  }

  @Override
  public SeedApiMessagesPQuantDataListResponse clone() {
    return (SeedApiMessagesPQuantDataListResponse) super.clone();
  }

}
