/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-17 at 19:02:29 UTC 
 * Modify at your own risk.
 */

package com.appspot.umichseed.seed.model;

/**
 * Model definition for SeedApiMessagesAlertListResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the seed. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SeedApiMessagesAlertListResponse extends com.google.api.client.json.GenericJson {

  /**
   * ProtoRPC message definition to represent a previously triggered alert
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<SeedApiMessagesAlertResponse> alerts;

  static {
    // hack to force ProGuard to consider SeedApiMessagesAlertResponse used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(SeedApiMessagesAlertResponse.class);
  }

  /**
   * ProtoRPC message definition to represent a previously triggered alert
   * @return value or {@code null} for none
   */
  public java.util.List<SeedApiMessagesAlertResponse> getAlerts() {
    return alerts;
  }

  /**
   * ProtoRPC message definition to represent a previously triggered alert
   * @param alerts alerts or {@code null} for none
   */
  public SeedApiMessagesAlertListResponse setAlerts(java.util.List<SeedApiMessagesAlertResponse> alerts) {
    this.alerts = alerts;
    return this;
  }

  @Override
  public SeedApiMessagesAlertListResponse set(String fieldName, Object value) {
    return (SeedApiMessagesAlertListResponse) super.set(fieldName, value);
  }

  @Override
  public SeedApiMessagesAlertListResponse clone() {
    return (SeedApiMessagesAlertListResponse) super.clone();
  }

}
