/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-17 at 19:02:29 UTC 
 * Modify at your own risk.
 */

package com.appspot.umichseed.seed.model;

/**
 * ProtoRPC message definition to represent a set of survey responses
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the seed. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SeedApiMessagesPQualDataPut extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long a1;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("time_taken")
  private com.google.api.client.util.DateTime timeTaken;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getA1() {
    return a1;
  }

  /**
   * @param a1 a1 or {@code null} for none
   */
  public SeedApiMessagesPQualDataPut setA1(java.lang.Long a1) {
    this.a1 = a1;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public SeedApiMessagesPQualDataPut setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getTimeTaken() {
    return timeTaken;
  }

  /**
   * @param timeTaken timeTaken or {@code null} for none
   */
  public SeedApiMessagesPQualDataPut setTimeTaken(com.google.api.client.util.DateTime timeTaken) {
    this.timeTaken = timeTaken;
    return this;
  }

  @Override
  public SeedApiMessagesPQualDataPut set(String fieldName, Object value) {
    return (SeedApiMessagesPQualDataPut) super.set(fieldName, value);
  }

  @Override
  public SeedApiMessagesPQualDataPut clone() {
    return (SeedApiMessagesPQualDataPut) super.clone();
  }

}
